FROM tensorflow/tensorflow:2.17.0-gpu

RUN apt-get update && apt-get install -y --no-install-recommends git && rm -rf /var/lib/apt/lists/*

COPY requirements.pinns.txt /tmp/requirements.pinns.txt
RUN pip install --no-cache-dir --ignore-installed blinker -r /tmp/requirements.pinns.txt

WORKDIR /app

ENTRYPOINT ["python", "run_pinns.py"]