FROM tensorflow/tensorflow:2.17.0-gpu

COPY requirements.pinns.txt /tmp/requirements.pinns.txt
RUN pip install --no-cache-dir -r /tmp/requirements.pinns.txt

WORKDIR /app

ENTRYPOINT ["python", "PINN_LinearElasticity.py"]